// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OEMEVWarrantyManagement.Infrastructure.Persistence;

#nullable disable

namespace OEMEVWarrantyManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250924200140_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TypeAppointmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TypeAppointmentId");

                    b.HasIndex("VIN");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SCStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SCTechID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SCStaffId");

                    b.HasIndex("SCTechID");

                    b.ToTable("Assignment", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.CarConditionCurrent", b =>
                {
                    b.Property<Guid>("WarrantyRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WarrantyRequestId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("CarConditionCurrents", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.CarInfo", b =>
                {
                    b.Property<string>("VIN")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("VIN");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ModelId");

                    b.ToTable("CarInfo", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.CarModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CarModels");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.DeliveryPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateReceive")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSend")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("StaffReceive")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StaffSend")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WorkPlaceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StaffReceive");

                    b.HasIndex("StaffSend");

                    b.HasIndex("WorkPlaceId");

                    b.ToTable("DeliveryParts", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WorkPlacesId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("WorkPlacesId");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.Image", b =>
                {
                    b.Property<Guid>("CarConditionCurrentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilePath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CarConditionCurrentId", "FilePath");

                    b.ToTable("Images", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.PartType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PartTypes", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.PartTypeModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PartTypeId");

                    b.ToTable("PartTypeModels", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.Parts", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("DeliveryPartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartTypeModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("RequestPartsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryPartId");

                    b.HasIndex("PartTypeModelId");

                    b.HasIndex("RequestPartsId");

                    b.ToTable("Parts", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.PartsReplacement", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartTypeModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("RecallHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WarrantyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SerialNumber");

                    b.HasIndex("PartTypeModelId");

                    b.HasIndex("RecallHistoryId");

                    b.HasIndex("WarrantyId");

                    b.ToTable("PartsReplacement", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.Recall", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EVMStaffId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfCars")
                        .HasColumnType("int");

                    b.Property<string>("PartReplacementId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recall", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.RecallHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmpoloyeeSCStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecallId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("Id");

                    b.HasIndex("EmpoloyeeSCStaffId");

                    b.HasIndex("RecallId");

                    b.HasIndex("VIN");

                    b.ToTable("RecallHistories", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.RecallHistoryEmployee", b =>
                {
                    b.Property<Guid>("RecallHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RecallHistoryId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("RecallHistoryEmployees");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.RecallPartTypeModel", b =>
                {
                    b.Property<string>("RecallId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PartTypeModelId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RecallId", "PartTypeModelId");

                    b.HasIndex("PartTypeModelId");

                    b.ToTable("RecallPartsReplacements", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.RequestPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EVMStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SCStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EVMStaffId");

                    b.HasIndex("SCStaffId");

                    b.ToTable("RequestParts", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.TypeAppointment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TypeAppointments", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.Warranty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeSCStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequestWarrantyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("WarrantyRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeSCStaffId");

                    b.HasIndex("RequestWarrantyId");

                    b.HasIndex("WarrantyRecordId");

                    b.ToTable("Warranties", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.WarrantyEmployee", b =>
                {
                    b.Property<Guid>("WarrantyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WarrantyId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("WarrantyEmployees");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.WarrantyPartsReplacement", b =>
                {
                    b.Property<Guid>("WarrantyId")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PartsReplacementId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("WarrantyId", "PartsReplacementId");

                    b.HasIndex("PartsReplacementId");

                    b.ToTable("WarrantyPartsReplacement", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.WarrantyPolicy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Coverage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PeriodInMonths")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WarrantyPolicies", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.WarrantyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("WarrantyPolicyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("VIN");

                    b.HasIndex("WarrantyPolicyId");

                    b.ToTable("WarrantyRecord", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.WarrantyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EVMStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SCStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("Id");

                    b.HasIndex("EVMStaffId");

                    b.HasIndex("SCStaffId");

                    b.HasIndex("VIN");

                    b.ToTable("WarrantyRequests", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.WorkPlacePartTypeModel", b =>
                {
                    b.Property<string>("WorkPlacesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PartTypeModelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("WorkPlacesId", "PartTypeModelId");

                    b.HasIndex("PartTypeModelId");

                    b.ToTable("WorkPlacePartTypeModels(PartInStock)", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.WorkPlaces", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("WorkPlaces", (string)null);
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.TypeAppointment", "TypeAppointment")
                        .WithMany("Appointments")
                        .HasForeignKey("TypeAppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.CarInfo", "CarInfo")
                        .WithMany("Appointments")
                        .HasForeignKey("VIN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarInfo");

                    b.Navigation("Customer");

                    b.Navigation("TypeAppointment");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.Assignment", b =>
                {
                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.Employee", "EmployeeSCStaff")
                        .WithMany("AssignmentsAsSCStaff")
                        .HasForeignKey("SCStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.Employee", "EmployeeSCTech")
                        .WithMany("AssignmentsAsSCTech")
                        .HasForeignKey("SCTechID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmployeeSCStaff");

                    b.Navigation("EmployeeSCTech");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.CarConditionCurrent", b =>
                {
                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.Employee", "EmployeeTechnician")
                        .WithMany("CarConditionCurrents")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.WarrantyRequest", "WarrantyRequest")
                        .WithOne("CarConditionCurrent")
                        .HasForeignKey("OEMEVWarrantyManagement.Domain.Entities.CarConditionCurrent", "WarrantyRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeTechnician");

                    b.Navigation("WarrantyRequest");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.CarInfo", b =>
                {
                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.Customer", "Customer")
                        .WithMany("CarInfos")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.CarModel", "CarModel")
                        .WithMany("CarInfos")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModel");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.Customer", b =>
                {
                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.Employee", "Employee")
                        .WithMany("Customer")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.DeliveryPart", b =>
                {
                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.Employee", "StaffReceiveEmployee")
                        .WithMany("DeliveryPartsReceive")
                        .HasForeignKey("StaffReceive")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.Employee", "StaffSendEmployee")
                        .WithMany("DeliveryPartsSend")
                        .HasForeignKey("StaffSend")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.WorkPlaces", "WorkPlaces")
                        .WithMany("DeliveryParts")
                        .HasForeignKey("WorkPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffReceiveEmployee");

                    b.Navigation("StaffSendEmployee");

                    b.Navigation("WorkPlaces");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.Employee", b =>
                {
                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.WorkPlaces", "WorkPlaces")
                        .WithMany("Employees")
                        .HasForeignKey("WorkPlacesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("WorkPlaces");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.Image", b =>
                {
                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.CarConditionCurrent", "CarConditionCurrent")
                        .WithMany("Images")
                        .HasForeignKey("CarConditionCurrentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarConditionCurrent");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.PartTypeModel", b =>
                {
                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.PartType", "PartType")
                        .WithMany("PartTypeModels")
                        .HasForeignKey("PartTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartType");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.Parts", b =>
                {
                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.DeliveryPart", "DeliveryPart")
                        .WithMany("Parts")
                        .HasForeignKey("DeliveryPartId");

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.PartTypeModel", "PartTypeModels")
                        .WithMany("Parts")
                        .HasForeignKey("PartTypeModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.RequestPart", "RequestPart")
                        .WithMany("Parts")
                        .HasForeignKey("RequestPartsId");

                    b.Navigation("DeliveryPart");

                    b.Navigation("PartTypeModels");

                    b.Navigation("RequestPart");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.PartsReplacement", b =>
                {
                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.PartTypeModel", "PartTypeModel")
                        .WithMany("PartsReplacements")
                        .HasForeignKey("PartTypeModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.RecallHistory", "RecallHistory")
                        .WithMany("PartsReplacements")
                        .HasForeignKey("RecallHistoryId");

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.Warranty", "Warranty")
                        .WithMany("PartsReplacements")
                        .HasForeignKey("WarrantyId");

                    b.Navigation("PartTypeModel");

                    b.Navigation("RecallHistory");

                    b.Navigation("Warranty");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.RecallHistory", b =>
                {
                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.Employee", "EmployeeStaffs")
                        .WithMany("RecallHistoriesAsSCStaff")
                        .HasForeignKey("EmpoloyeeSCStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.Recall", "Recall")
                        .WithMany("RecallHistories")
                        .HasForeignKey("RecallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.CarInfo", "CarInfo")
                        .WithMany("RecallHistories")
                        .HasForeignKey("VIN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarInfo");

                    b.Navigation("EmployeeStaffs");

                    b.Navigation("Recall");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.RecallHistoryEmployee", b =>
                {
                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.Employee", "Employee")
                        .WithMany("RecallHistoryEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.RecallHistory", "RecallHistory")
                        .WithMany("RecallHistoryEmployees")
                        .HasForeignKey("RecallHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("RecallHistory");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.RecallPartTypeModel", b =>
                {
                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.PartTypeModel", "PartTypeModel")
                        .WithMany("RecallPartTypeModels")
                        .HasForeignKey("PartTypeModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.Recall", "Recall")
                        .WithMany("RecallPartTypeModels")
                        .HasForeignKey("RecallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartTypeModel");

                    b.Navigation("Recall");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.RequestPart", b =>
                {
                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.Employee", "EVMStaff")
                        .WithMany()
                        .HasForeignKey("EVMStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.Employee", "SCStaff")
                        .WithMany("RequestParts")
                        .HasForeignKey("SCStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EVMStaff");

                    b.Navigation("SCStaff");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.Warranty", b =>
                {
                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.Employee", "EmployeeSCStaff")
                        .WithMany("WarrantiesAsSCTech")
                        .HasForeignKey("EmployeeSCStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.WarrantyRequest", "RequestWarranty")
                        .WithMany("Warranties")
                        .HasForeignKey("RequestWarrantyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.WarrantyRecord", "WarrantyRecord")
                        .WithMany("Warrantys")
                        .HasForeignKey("WarrantyRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeSCStaff");

                    b.Navigation("RequestWarranty");

                    b.Navigation("WarrantyRecord");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.WarrantyEmployee", b =>
                {
                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.Employee", "Employee")
                        .WithMany("WarrantyEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.Warranty", "Warranty")
                        .WithMany("WarrantyEmployees")
                        .HasForeignKey("WarrantyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Warranty");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.WarrantyPartsReplacement", b =>
                {
                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.PartsReplacement", "PartsReplacement")
                        .WithMany("WarrantyPartReplacements")
                        .HasForeignKey("PartsReplacementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.Warranty", "Warranty")
                        .WithMany("WarrantyPartReplacements")
                        .HasForeignKey("WarrantyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PartsReplacement");

                    b.Navigation("Warranty");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.WarrantyRecord", b =>
                {
                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.Customer", "Customer")
                        .WithMany("WarrantyRecords")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.CarInfo", "CarInfo")
                        .WithMany("WarrantyRecords")
                        .HasForeignKey("VIN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.WarrantyPolicy", "WarrantyPolicy")
                        .WithMany("WarrantyRecords")
                        .HasForeignKey("WarrantyPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarInfo");

                    b.Navigation("Customer");

                    b.Navigation("WarrantyPolicy");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.WarrantyRequest", b =>
                {
                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.Employee", "EVMStaff")
                        .WithMany("WarrantyRequestsAsEVMStaff")
                        .HasForeignKey("EVMStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.Employee", "SCStaff")
                        .WithMany("WarrantyRequestsAsSCStaff")
                        .HasForeignKey("SCStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.CarInfo", "CarInfo")
                        .WithMany("WarrantyRequests")
                        .HasForeignKey("VIN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarInfo");

                    b.Navigation("EVMStaff");

                    b.Navigation("SCStaff");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.WorkPlacePartTypeModel", b =>
                {
                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.PartTypeModel", "PartTypeModel")
                        .WithMany("WorkPlacePartTypeModels")
                        .HasForeignKey("PartTypeModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OEMEVWarrantyManagement.Domain.Entities.WorkPlaces", "WorkPlaces")
                        .WithMany("WorkPlacePartTypeModels")
                        .HasForeignKey("WorkPlacesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartTypeModel");

                    b.Navigation("WorkPlaces");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.CarConditionCurrent", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.CarInfo", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("RecallHistories");

                    b.Navigation("WarrantyRecords");

                    b.Navigation("WarrantyRequests");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.CarModel", b =>
                {
                    b.Navigation("CarInfos");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("CarInfos");

                    b.Navigation("WarrantyRecords");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.DeliveryPart", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.Employee", b =>
                {
                    b.Navigation("AssignmentsAsSCStaff");

                    b.Navigation("AssignmentsAsSCTech");

                    b.Navigation("CarConditionCurrents");

                    b.Navigation("Customer");

                    b.Navigation("DeliveryPartsReceive");

                    b.Navigation("DeliveryPartsSend");

                    b.Navigation("RecallHistoriesAsSCStaff");

                    b.Navigation("RecallHistoryEmployees");

                    b.Navigation("RequestParts");

                    b.Navigation("WarrantiesAsSCTech");

                    b.Navigation("WarrantyEmployees");

                    b.Navigation("WarrantyRequestsAsEVMStaff");

                    b.Navigation("WarrantyRequestsAsSCStaff");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.PartType", b =>
                {
                    b.Navigation("PartTypeModels");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.PartTypeModel", b =>
                {
                    b.Navigation("Parts");

                    b.Navigation("PartsReplacements");

                    b.Navigation("RecallPartTypeModels");

                    b.Navigation("WorkPlacePartTypeModels");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.PartsReplacement", b =>
                {
                    b.Navigation("WarrantyPartReplacements");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.Recall", b =>
                {
                    b.Navigation("RecallHistories");

                    b.Navigation("RecallPartTypeModels");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.RecallHistory", b =>
                {
                    b.Navigation("PartsReplacements");

                    b.Navigation("RecallHistoryEmployees");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.RequestPart", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.Role", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.TypeAppointment", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.Warranty", b =>
                {
                    b.Navigation("PartsReplacements");

                    b.Navigation("WarrantyEmployees");

                    b.Navigation("WarrantyPartReplacements");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.WarrantyPolicy", b =>
                {
                    b.Navigation("WarrantyRecords");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.WarrantyRecord", b =>
                {
                    b.Navigation("Warrantys");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.WarrantyRequest", b =>
                {
                    b.Navigation("CarConditionCurrent");

                    b.Navigation("Warranties");
                });

            modelBuilder.Entity("OEMEVWarrantyManagement.Domain.Entities.WorkPlaces", b =>
                {
                    b.Navigation("DeliveryParts");

                    b.Navigation("Employees");

                    b.Navigation("WorkPlacePartTypeModels");
                });
#pragma warning restore 612, 618
        }
    }
}
